# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          xcodebuild \
            -scheme LuminaKit \
            -destination 'generic/platform=iOS' \
            build

      - name: Test
        run: |
          SIM_ID=$(xcrun simctl list devices available | grep -E 'iPhone' | head -n 1 | sed -E 's/.*\(([-A-F0-9]+)\).*/\1/')
          echo "Testing on Simulator ID: $SIM_ID"
          xcodebuild \
            -scheme LuminaKit \
            -destination "id=$SIM_ID" \
            test
